### ISSUE TITLE
Question: ArkUI related API support

### ISSUE THREAD

**Issue by zhongyr** [openharmony-rs/ohos-sys#13]
Are ArkUI related bindings within the scope of this repo? Or an isolated repo is needed (maybe sth like ohos-arkui )?

**Comment by jschwe** [comment]
In principle all native components from the OH SDK are in scope of this repository.
To keep the crate-size of ohos-sys on crates.io reasonable, I think `arkui` should also be an inidividual crate (similar to `drawing`, which is also it's own crate in this repository, and additionally re-exported by `ohos-sys`)

**Comment by zhongyr** [comment]
Make sense.
